### PR TITLE
fix: format root files only

### LINKED ISSUE #98: `gts check/fix` uses a list of files created by tslint
See below comment

~On my mac, `gts check` exits with code 0 before checking all files [here](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/621). On linux this doesn't happen, and I get my clang-format error reports.~

~I combed `gts` dependencies for `process.exit` calls but couldn't find any. I believe unresolved Promises are somehow being ignored, and the event loops drains fully. Unsure about this...~

### PR DESCRIPTION
**Pull request by kjin**
Fixes #98

We should use `getRootFileNames` instead of `getSourceFiles` when retrieving a list of files to format; the latter gets every files in the dependency graph constructed from files included in `tsconfig.json`.

### CODE REVIEW

File: src/format.ts [hunk 1]
```diff
@@ -73,6 +71,7 @@ function fixFormat(srcFiles: string[]): Promise<boolean> {
  * @param srcFiles list of source files
  */
 function checkFormat(srcFiles: string[]): Promise<boolean> {
+  console.log(srcFiles);
```
Comment (ofrobots) [inline src/format.ts]: Errant log?

File: test/fixtures/kitchen/src/server.ts [hunk 2]
```diff
@@ -1 +1 @@
-  const isThisTypeScript = true
+  export const isThisTypeScript = true
```
Comment (ofrobots) [inline test/fixtures/kitchen/src/server.ts]: why was this change needed?

File: test/test-format.ts [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+  yes: false,
+  no: false,
+  logger: {log: console.log, error: console.error, dir: nop}
+};
+
+test.serial('format should return false for ill-formatted files', async t => {
+  await withFixtures(
+      {
+        'tsconfig.json': JSON.stringify({files: ['a.ts']}),
+        'a.ts': 'export const foo = 2;  '
```
Comment (jinwoo) [inline test/test-format.ts]: Is this ill-formatted because of the trailing spaces? Can you add a comment for that so that future readers don't accidentally delete the spaces?

Comment (jinwoo) [reply test/test-format.ts]: Actually I should've put this comment in line 51 below because if someone accidentally removes the trailing spaces there, the test will still pass.

**Comment by kjin** [comment]
@jinwoo @ofrobots PTAL

File: src/format.ts [hunk 4]
```diff
@@ -32,12 +32,10 @@ export async function format(
   const program = createProgram(options);
   const srcFiles = files.length > 0 ?
       files :
-      program.getSourceFiles()
-          .map(sourceFile => sourceFile.fileName)
-          .filter(f => !f.endsWith('.d.ts'));
+      program.getRootFileNames().filter(f => !f.endsWith('.d.ts'));
```
Comment (jinwoo) [inline src/format.ts]: Can you briefly comment here on why only root files should be formatted?

File: test/test-format.ts (hunk 3 above)
Comment (jinwoo) [reply test/test-format.ts]: I'd put the same comment here too so that people can easily understand why this line must fail :)

File: src/format.ts (hunk 4 above)
Comment (kjin) [reply src/format.ts]: Done
